[package]
name = "line-bar"
version = "0.1.0"
authors = ["Zhong Huiping <jxwazxzhp@126.com>"]
edition = "2021"
license = "MIT"

[dependencies]
colored = "2.0.4"
ansi_term = "0.12.1"
unicode-width = "0.1.10"
zellij-tile = "0.38.1"
zellij-tile-utils = "0.38.1"
